---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: docker.io/nginxinc/nginx-unprivileged:latest
        name: nginx-unprivileged
